project:
  type: website

website:
  title: "DCHS Invest "
  navbar:
    logo: "hidden-invest-logo.png"
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: guide.qmd
        text: Guide
      - href: about.qmd
        text: About Us
      - href: first-analysis.qmd
        text: Meeting Research
        
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



