project:
  type: website

website:
  title: "DCHS Invest "
  navbar:
    logo: "hidden-invest-logo.png"
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: guide.qmd
        text: Guide
      - href: analysis.qmd
        text: Research
      - href: december-roundup.qmd
        text: December Report
        
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    grid:
      body-width: 880px



