project:
  type: website

website:
  title: "DCHS Invest "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - guide.qmd
      - online-sections.qmd
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



