project:
  type: website

website:
  title: "DCHS Investment Club "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - guide.qmd
      - tutorial1.qmd
      - tutorial2.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



