project:
  type: website

website:
  title: "DCHS Invest "
  navbar:
    logo: "hidden-invest-logo.png"

    title: false
    left:
      - href: index.qmd
        text: Home
      - href: guide.qmd
        text: Guide
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



