---
title: ""
format: html
---

<div class="alert1">
<span class="something1">**This page was recently updated**</span></div>  

___

<span class="smalltext-black">List of investment topics relating to the stock market (& analyzing stocks/companies)</span>
<div class="small-table">
| **Current**                          |                               |   **Advanced (2025-2026)**                            |
|------------------------------------|-----------------------------------------------|-------------------------------------------|
| - The stock market                 | - Dividends                                   | - Option Trading                          |
| - Buying & Selling                 | - Indexes, index funds, ETFs                  | - EMH                                     |
| - Shorting & Covering              | - Volatilities and risk                       | - Fundamental Analysis <span class="small-text-black">(continued)</span>|
| - Factors affecting share value    | - Option trading (puts & calls)               | - RESEARCHING COMPANIES                   |
| - Acquisitions (impact)            | - Intrinsic value                             | - Protecting against manipulation         |
| - Volume, market-cap, PE ratio     | - Fundamental Analysis (earnings, financials) | - Univeristy of Pennsylvania (uPenn) Competition Opportunity                                         |
|                                    | - Insider reports                             |                                           |
</div>
---

<div class="alert3">
<span class="something1">Throughout meetings, we cover the topics listed above to provide a detailed understanding of the stock market. Later, once proficient in each topic, analysis of certain companies and their stock is possible, allowing you to find and choose strong investments.

Our investments have returned +54.88% since July 2024</div>

:::{.callout-important collapse="true" appearance="simple"}
### Financial Resources
Tracking companies and stocks: <a href="https://finance.yahoo.com" target="_blank" rel="noopener noreferrer" style="color: #006400">finance.yahoo.com</a>  
Tracking future earnings expectations: <a href="https://www.nasdaq.com/market-activity" target="_blank" rel="noopener noreferrer" style="color: #006400">nasdaq.com/market-activity</a>
:::


<br>

<div class="nav-right">
| <a href="https://invest.quarto.pub/#:~:text=delay.%0ALearn%20more-,Join/Updates,-%5BDirects%20to%20external" rel="noopener noreferrer" style="color: #373737">Updates</a> | [Home](index.qmd){style="color: #373737;"} | [About](about.qmd){style="color: #373737;"}
</div>