---
title: "Section-1"
format: html
author: "Aedan L"
css: styles.css
---

<span class="border-type-banner">
**Important Stock Market Basics & Review**
</span>  

### Intro
This section covers the foundations of the stock market and information about the stock market.  
Past meeting contents are also available on this page.

### Contents of this Section
<span class = "smalltext-black">Preview what is ahead.</span>  
<div class="info-box">
**1:** <span class = "highlight1">What The Stock Market Is</span>  
**2:** <span class = "highlight1">Share Prices</span>  
**3:** <span class="highlight1">Market-Cap & Volume</span>  
**4:** <span class = "highlight1">Volatility & Indexes</span></div>

*For intermediate to more advanced traders, this section would serve only as a refresher.*  

### The Stock Market - (Core)
The stock market is a massive financial network that allows people to buy and sell different companies.

The stock market is comprised thousands of **companies**, allowing anyone to buy or sell portions of companies.

Since many companies are huge, some having valuations in the $100,000,000,000's, the stock market allows anyone to purchase and exchange small **shares** of these companies. These shares represent your (*partial*) ownership of these companies, and every share carries a monetary value.

<div class="tip-box">
On the stock market, companies are referred to as stocks.  
**A Company = A Stock**</div>

**The Sole Gole:**  
The goal of investing is to invest in shares of companies **you believe in**, hoping that the value of the company increases, in turn causing your shares (holdings) to increase in value.

Throughout the year, we will discuss strategies on successfully analyzing good investments (stock choices)

### Share Prices
Every share of a company has its unique price.  

**For example: **
Apple's (AAPL) share price is $225/share.
Chipotle's (CMG) share price $56/share.

This means that to own shares of AAPL, you would need to invest $225 for each share you plan to buy.

**Share Price Fluctuation:**  
Remember, to profit from the stock market, your shares need to increase in value.

This brings us to Share Price Fluctuation/Movement.

The value of any shares of stock are always changing. On one day they could go up 3%, on the next day they could go down 2.5%. Profit is *never* guaranteed, but you can take steps to improve your accuracy.

<div class="tip-box">
At the core, share price increases with company growth and success  
We will go in-depth on the specifics in future sections</div>

<span class="smalltext-black">**Did you know Elon Musk has 200 million shares of Tesla (TSLA)?  
Companies often have hundreds of millions of shares total outstanding.** </span>

<div class="tip-box2">**Important**:  
Do not compare two different stocks' share prices. Different companies have different share prices, and **comparing two different share prices of two different companies is useless**.

For example, Costco (COST)'s share price is $900/share, but Apple (AAPL)'s is $225/share.  
Does this mean Costco is a bigger company than Apple? **No**.</div>

### Market-Cap
Market-cap is an important piece of information to consider before any investment decision.

Market-cap represents the total value of the company, **Market-Cap = Valuation**.

<div class="tip-box">
Market Cap = share price * # of shares</div>

**Why Is It Important?**  
Market-cap determines the company's size, based on what the stock market believes the company is worth.
Paired with (*)quantitative data, it lets us measure the fair value of a stock.

<span class="smalltext-black">*(will be covered when we discuss Fundamental Analysis)</span>

<div class="tip-box2">
**A key thing to know:**  
Share price moves *proportionally* to market-cap  
This means a <span class="highlight1">**+20%**</span> jump in share price means a <span class="highlight1">**+20%**</span> jump in market-cap  

Comparing two different stocks' market-caps is okay.</div>

    
If a company has 1 million shares outstanding and the share price goes up from $100 to $120, the market-cap would increase as follows:

- Initial market-cap: 1,000,000 shares * $100/share = $100,000,000
- New market-cap: 1,000,000 shares * $120/share = $120,000,000

This shows how a change in the share price directly affects the market-cap. 

### Volume
Volume is the total # of shares traded within a day.
Stocks with higher volume are more active and more well-known.

Volume isn't all that important.

### Volatitility
Volatility is important, though, as it measures a stock's risk.
A stock/company with a higher volatility moves more rapidly with bigger %change.

<span class = "something1">**For example:**  
A stock with a lower volatility may see **~1-2%** movement each day,  
while a stock with a higher volatility could see **>5%** movement.</span>

If you prefer your portfolio to aggressively grow VS remain stable, volatility is a key factor to consider.

---

### Indexes
Indexes are an incredibly **important** part of the stock market.

Indexes generally measure the overall stock market's performance, tracking hundreds of companies at once.
You could almost think of them as a broad **basket of stocks**

The three major indexes are the: <span class="highlight2">**S&P 500**, **NASDAQ**, and **DOW**</span>  
<span class="something1">The <span class="highlight2_09">S&P 500</span> tracks the 500 largest US companies.</span>  
<span class="something1">The <span class="highlight2_09">NASDAQ</span> tracks technology and software companies</span>  
<span class="something1">The <span class="highlight2_09">DOW</span> tracks the 30 biggest US companies</span>

Indexes are **steady and stable** investments that rise slowly over time. They are a great alternative to cash if you dislike the risk associated with choosing specific stocks/companies.

<div class="tip-box">
We will continue to talk indexes and ETFs in the future</div>


### --- Temporary Conclusion ---
You've finished reading this section for "Important Stock Market Basics & Review".  
This section covered the essentials related to stocks, which will be crucial for our future material and discussions.

<span class="smalltext-black">
**Last Revised:** 12/27/2024</span>

